### PR TITLE
Updated to Rails 5.2 and added avatar for users

### PR DESCRIPTION
**Pull request by amanmibra**
**Warning**: _Since there has been an update to core services, please make sure that you follow the steps below when you are testing this PR and once this has been pushed to `staging`. If the steps are not followed, it is likely that development will not function for you locally._

## Setup (required)
As their has been an critical update to our rails dependency (as well as others). Please do the following:
1. Run `docker-compose down`
2. Run `docker-compose build`
3. Run `yarn flush`
4. Run `yarn dev:start` to start the server

## Description

Updated Rails 5.1 ~> Rails 5.2 in order to use new `ActiveStorage` library to upload files to models. In this PR, it focuses on both installing the ActiveStorage library and implementing it to the User model in order to allow users to have and upload avatars to their accounts. This also updates the availability dropdown to show user avatars.

## Motivation and Context

See trello card: https://trello.com/c/YySuYMuE/32-add-profile-picture-for-team-and-user-models

## How Has This Been Tested?

1. Go to User Profile, and see lack of profile picture.
2. Go to "Edit User Avatar", and upload and save an image.
3. Return to previous pane, and see that picture is now there.
4. Try to add or update shift, see that user availability dropdown now has all of the team mate's avatars.

## Screenshots (if appropriate):
image

image

image

image

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by vinitbytheminute — COMMENTED** [review]
**Review**
Thank you for putting time in and adding the ActiveStorage Library to allow users to add avatars. While this is a great idea, I wanted to go over some areas of possible concerns while loging in, adding my avatar under User Profile, and Updating/Creating at shift.

**Creating a Profile**
When I tried to Sign Up originally, I was unable to add an email without this "Error Tag" showing up for every email I typed in. I typed in "Amanisanoraage@duke.edu" and this same error arised.
screen shot 2019-01-02 at 11 13 56 am

 However, I was able to log in under vrp25@duke.edu ( a random email). When I logged out and tried to create another Profile, the Email Error Tag did not show up. I am unsure if this is a once and one time glitch, but I wanted to bring this to your attention in case you think this is a concern. 

**Adding Avatar**
I was unable to save any avatar I tried uploading. I tried a total of 5 images of different sizes.  None worked.
screen shot 2019-01-02 at 11 15 44 am

**Adding/Creating Shifts**

When viewing a card or trying to create a shift, the card display is up in the right corner. This cuts off half of the Card Display. 
screen shot 2019-01-02 at 11 16 27 am

As shown in your PR, the image default shows up next to each persons name in the dropdown. 
screen shot 2019-01-02 at 11 39 44 am

**Code**
Based on my standards, your code is very clean. Great job Aman

**Comment by amanmibra** [comment]
Please share what the console says when those error appear. It may be something on your end. @vinitbytheminute

**Review by vinitbytheminute — COMMENTED** [review]
@amanmibra 
### **Avatar**
I will walk through what is occuring in my console as I try to update my profile picture in 'Edit User Avatar'.

**Process**
I went to 'Edit User Avatar'
screen shot 2019-01-02 at 12 01 42 pm

Then I tried to pick a picture from my computer
screen shot 2019-01-02 at 12 01 57 pm

The picture has been pick
screen shot 2019-01-02 at 12 02 13 pm
ed

Try to save picture and a post error arises
screen shot 2019-01-02 at 12 02 44 pm
 
Nothing Saved
screen shot 2019-01-02 at 12 07 40 pm

**Comment by vinitbytheminute** [comment]
@amanmibra 
### **Update Shift**

**Process**
Here are snapshots of my console as I try to update a shift in the calendar view.

Console when I am on the Calendar view
screen shot 2019-01-02 at 12 00 08 pm

Udated 12:57 to 5 shift
screen shot 2019-01-02 at 12 00 25 pm

Updating shift with Rajen
screen shot 2019-01-02 at 12 00 35 pm
screen shot 2019-01-02 at 12 00 44 pm

Once updated calendar View. Checking shift as well to see update
screen shot 2019-01-02 at 12 00 53 pm
screen shot 2019-01-02 at 12 01 05 pm

**Review by vinitbytheminute — APPROVED** [review]
Looks good!

**Comment by mafuvadze** [comment]
Very nice Aman. Couple suggestions:
- Users should be allowed to set up a profile pic when they sign up
- Make the profile pic circular so it matches the default one

Otherwise nice work. Upgrade to 5.2 went flawlessly

**Review by mafuvadze — APPROVED** [review]

**Comment by amanmibra** [comment]
@mafuvadze What do mean circular? Are you talking about the dropdown being circular while the other uses of avatar are not? If so, then I will also consider making dropdown non-circular as well.

**Pull request merged**
