### PR TITLE
Schedule Automation

### PR DESCRIPTION
**Pull request by amanmibra**
## Description

The feature to automatically create shifts based on user shifts, utilizing the Olson algorithm (check the [gthc gem](https://github.com/gthc/gthc)).

## Motivation and Context

One of our biggest, new features of this year. Helps with one of the most difficult tasks of tenting, going through people's availability and creating shifts for them.

## How Has This Been Tested?

1.  Run `yarn flush` to generate availabilities for fake generated users.
    a. Join a team with passcode "abc123" and create your own shifts.
2. Go to Calendar
3. Click the "Generate Shifts" button on the calendar, choose your settings (date range, type of tenting, and clearing other shifts) and see the shifts being generated.

## Screenshots (if appropriate):
image

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by shamystic — CHANGES_REQUESTED** [review]
Nice work man! Seems to work smoothly, it's awesome that we have this up and running. :) 
One thing that I think is a pretty big deal is the Calendar visual experience of GTHC, and right now there are two huge things I think it misses: 
1. I think that each shift should have not just the times which it has right now, but the users of the shift. These should be visible without having to click on the shift. This is a big user experience thing: assigning users to shifts is the bread and butter of our application. These should be seen easily and immediately. If we can show the times of the shift in the frontend calendar, we easily can show the list of users as well. Something like "4:00 PM - 4:30 PM: Shamikh, Aman, Vinit". I also think this text should be in bold. 
2. The shifts on the calendar should be different colors. After discussing with Vinit, just two colors is enough: a different color for the current user's shifts, and the blue for everyone else's shift is good. This makes it easy to differentiate what's important for the users. 
A couple other recommendations I have right off the bat: 
1. Make the "Generate Shifts' button a different color than blue, and maybe make the button smaller by not having it take up the full length of the page, but keep it centered. Instead of using the full width of the page you could maybe make the button green, and make the "Generate Shifts" text larger. Even if you do decide to take up the full width of the page (which is fine because it is consistent with other styling) I think we should make the text larger and the button green/another satisfying color. 
2. (Text when you click Generate Shift) I strongly think we should change "GTHC's Tenting Algorithm" → "GTHC's Schedule Automation". The word "Algorithm" should not be anywhere in our frontend. 
3. (Text on the shift in the calendar) We should change "Generated by Olson Algorithm" → "GTHC Generated Shift".

**Comment by rikkikendall** [comment]
Aman, great work on this. Sorry it took a while for me to review, been working on modal stuff. I noticed a couple things as I was playing around in staging. Wanted to bring them up. 

Screen Shot 2019-12-29 at 10 20 41 AM

So, noticed that when I log out of my Duke account, it takes me to this page where I am asked "Am I sure if I want to log out." Lets say in this situation I didn't mean to log out, and I want to return to the screen I was just on. I pushed Cancel, it doesn't redirect anywhere. I was wondering if there was a way to specify that the Cancel button redirects to the Home page or something like that. Currently, the only way to go back into the app is if I go up to the Login button and push Log In with my NetID again. It defeats the purpose of having that Cancel button option. 

Screen Shot 2019-12-29 at 10 24 37 AM

I generated shifts for myself making myself somewhat available and available at the same time. My generated shifts were on my dashboard with directions stating, "Feel free to edit these by pushing the update button." That button doesnt exist on the dashboard card, I know it exists when I go find that shift on the calendar. I think its a bit confusing and I just wanted to bring it up. 

Maybe it would be a bit confusing but maybe for the future we can click on that card and it'll take us to that shift modal in the calendar.

**Comment by amanmibra** [comment]
@rikkikendall Thanks for the review but this has been closed for two days now. This is probably something worth making an issue page for, so if you could do that, that would be great.

**Comment by amanmibra** [comment]
Also your first point is not a GTHC design, if you have problems with that design, that is something you'd need to take to OIT, not GTHC.

**Pull request merged**
