### PR TITLE
Resolve Issue #6

### LINKED ISSUE #6: Complete the Integration of API to Calendar and Integration of Drag 'n Drop Addon
Refer to #3 for more detail on what needs to be done.

Overall, I need to implemented the PUT, and DELETE endpoints built in the the PR #3 and also add the DnD addon for the calendar which can be found here:

http://intljusticemission.github.io/react-big-calendar/examples/index.html#dnd

### PR DESCRIPTION
**Pull request by amanmibra**
Closes #6

#### Changes
1. Updating Shifts
   a. Clicking on any Shift, then clicking "Update", and update shift information is a live and functional feature.
    b. Update Shift time by dragging or dropping the event block on the Calendar.
2. Delete Shifts
    a. User can delete shifts by clicking the "Delete" button in the Shift View modal.
3. Fixed bug (a issue page was not mad, but it was discussed in PR #3) that would not allow the Create Shift Modal to open properly in some cases.

### CODE REVIEW

**Comment by amanmibra** [comment]
This PR also fixes the bug that @vinitbytheminute brought up, where there was a 'lag' between dragging a new event and the modal appearing.

**Comment by vinitbytheminute** [comment]
Here is the link to a video describing the bug i found: https://duke.box.com/s/sr5ebajdam5wdi9lx32rwr82g6im2xez

**Comment by vinitbytheminute** [comment]
Bugs Found 
1. Clicking on any Shift, then clicking "Update", and update shift information is a live and functional feature.
    a. When updating a shift and then changing a person, the shift gets updated half the time. For instance, if there are three members on a shift ("James","Kim","Miles") and we want to switch Miles out for "Jamie"....we press the update and switch out the user. However, half the time it works and half the time it does not work. Please address this
2. Update Shift time by dragging or dropping the event block on the Calendar.
Delete Shifts
  a. Once you drag an already created event from one location to another and press the event, the top description of the time does not change to the new starting time. However, I think the top of that section that "Shift on Date X at time X" should be changed to the users in the tent at the time.

**Comment by amanmibra** [comment]
@vinitbytheminute I would advise you to use markdown formatting in the future for your comments if you going to list stuff out by sections because it is really hard to read some of what you are saying. No big deal though.

Responding to your most recent comment:

1. Please share a video, I do not understand what you are trying to say here.

2. That seems unnecessary to me as the generated titles was added only to avoid any issues with API requests when we were in early API development. This (the generated titles when creating events) will be removed all together before production. In production, all titles will need to created by the users themselves.

Also, you mentioned something about editing times for the CreateView. That is not the purpose of this PR. One feature at a time, we are not going to stuff everything we want onto one PR.

**Comment by amanmibra** [comment]
Also please actually do an actual review. You can do this by clicking the "Files Changed" tab, and then click "Review Changes" afterwards. In there make your comments and observations, and make sure you click approve, deny, or request changes once you are done. @vinitbytheminute

**Pull request merged**
