### PR TITLE
WIP: Small Frontend fixes

### LINKED ISSUE #120: Frontend Fixes: login page scroll, phone number formatting, navbar clarity
**Describe the bug**
There are several front end issues that can be addressed to improve our app.
1. There is an unnecessary scrolling bar on the GTHC home page (before login). There is not enough content on the page to require a scroll bar, so this causes unnecessary clutter. This should be removed. 
image

2. Phone numbers are formatted incorrectly. Go to https://staging.gthc.io/app/team and view Team Table to observe this. We should be removing non-numeric characters from phone numbers before saving, and then use https://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_to_phone to render phone numbers in the front end. 
image

3. From a user experience perspective, the purpose of different pages on the app should be immediately obvious even before thorough exploration. Right now, it is not immediately obvious what the difference is before "Home" and "Dashboard", until the user clicks on Dashboard and sees team specific information. For better clarity, we should name Dashboard to something like "Tent Dashboard" or "Team Dashboard". I asked Vinit if this was looked into during his user testing, but he said it did not come up. However, it was brought to my attention when testing with one of my friends recently. We want to make the purpose of the page obvious even before exploration, since the user may not always want to explore. 
image

4. We should replace the login with NetID blue button with the high res version. If the tern who was assigned this task doesn't want to do it, we should just take care of it ourselves, just lmk and I will do it. 

**To Reproduce**
1. Go to https://gthc.io/login and maximize your window. The scroll bar should go away, but it does not. 
2. Go to https://staging.gthc.io/app/team and view Team Table to view phone numbers.

### PR DESCRIPTION
**Pull request by shamystic**
Closes #120, but is a work in progress. So far, fixes phone number issue. 

## Description
Formats phone numbers correctly upon user sign up.

## How Has This Been Tested?
Sign up and entering faulty phone numbers ("9-1.2,518--00-22")

### CODE REVIEW

**Comment by amanmibra** [comment]
Thanks for taking initiative bro

**Comment by amanmibra** [comment]
@shamystic is this ready, also this doesn't actually close #120 entirely does it. Does this PR fix the scroll?

**Comment by shamystic** [comment]
No it’s a WIP, wanted to see if you could help out with fixing the scroll. So far only addresses phone numbers

**Review by amanmibra — APPROVED** [review]
Let's skeddit

We will do scroll wheel in another PR

**Pull request merged**
